### PR TITLE
Update the container config by using Dev Container Features

### LINKED ISSUE #3: Add quarto support?
It would be useful to set up Quarto so that it can be used from within VSCode.
https://github.com/quarto-dev/quarto-vscode

~~Since quarto is not currently installed in `rocker/tidyverse` (it is bundled with RStudio Server but not added to the path), we will need to change the base image to `rocker/verse` or run `/rocker_scripts/install_quarto.sh` must be executed to install quarto cli.~~

Now `rocker/tidyverse:4.2` already has quarto cli installed!

### PR DESCRIPTION
**Pull request by eitsupi**
I have spent the last few months creating Dev Container Features and Templates for R.
https://github.com/rocker-org/devcontainer-features
https://github.com/rocker-org/devcontainer-templates

Since this repository has attracted the attention of R users, I thought it might be worthwhile to rewrite the container definition using Dev Container Features.
This change simplifies the Dockerfile.

In addition, the following changes were also made.

- Add quarto support. (closes #3)
- Use `postAttachCommand` instead of `postCreateCommand` (See rocker-org/devcontainer-images#17)

Also, since RStudio Server on this base image [opens `/workspaces` by default](https://github.com/rocker-org/devcontainer-images/blob/0f96958e422034576851e752d268744fca414ee1/src/rstudio/assets/rstudio-prefs.json#L6), #1 would also be closed.

cc @cboettig

### CODE REVIEW

**Comment by eitsupi** [comment]
@revodavid Could you take a look at this? Thanks.

**Comment by revodavid** [comment]
> @revodavid Could you take a look at this? Thanks.

Sure, I'll review now. (I've been on vacation for a few weeks.)

**Comment by revodavid** [comment]
@eitsupi The changes look good to me, but would you mind to persist the use of "ARG variant" in Dockerfile, since I call that out specifically in the slides for this talk? I'd like to keep the code consistent with the talk as given. Thanks for the contributions!

**Comment by eitsupi** [comment]
Thank you for your review. I modified it and confirmed it works with Codespaces.

**Pull request merged**
